alias pacUpdate="pacman -Syu"
alias pac="pacman -S"
alias pacSearch="pacman -Ss"
alias ll="ls -l --color=auto"
alias pacRemove="pacman -Rns"
alias pacList="pacman -Qe"
alias lsa="ls -a --color=auto"
alias startldm="systemctl start lightdm"
alias firefox="firefox &"
alias spac="sudo pacman -S"
alias spacUpdate="sudo pacman -Syu"
alias spacSearch="sudo pacman -Ss"
alias spacList="sudo pacman -Qe"
alias spacRemove="sudo pacman -Rns"
alias idaFree="./~/Tools/idafree-7.0/ida64"
